# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/image_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 600)
        MainWindow.setMinimumSize(QtCore.QSize(530, 600))
        MainWindow.setMaximumSize(QtCore.QSize(530, 600))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_container = QtWidgets.QLabel(self.centralwidget)
        self.image_container.setGeometry(QtCore.QRect(10, 20, 512, 512))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.image_container.setFont(font)
        self.image_container.setStyleSheet("border: 1px solid black")
        self.image_container.setText("")
        self.image_container.setObjectName("image_container")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 530, 511, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previous_iteration_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.previous_iteration_btn.setObjectName("previous_iteration_btn")
        self.horizontalLayout.addWidget(self.previous_iteration_btn)
        self.iteration_count_output = QtWidgets.QLabel(self.layoutWidget)
        self.iteration_count_output.setAutoFillBackground(False)
        self.iteration_count_output.setAlignment(QtCore.Qt.AlignCenter)
        self.iteration_count_output.setObjectName("iteration_count_output")
        self.horizontalLayout.addWidget(self.iteration_count_output)
        self.next_iteration_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.next_iteration_btn.setObjectName("next_iteration_btn")
        self.horizontalLayout.addWidget(self.next_iteration_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 530, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.save_image_action = QtWidgets.QAction(MainWindow)
        self.save_image_action.setObjectName("save_image_action")
        self.configuration_action = QtWidgets.QAction(MainWindow)
        self.configuration_action.setObjectName("configuration_action")
        self.menu.addAction(self.save_image_action)
        self.menu.addSeparator()
        self.menu.addAction(self.configuration_action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генератор фракталов"))
        self.previous_iteration_btn.setText(_translate("MainWindow", "<<<"))
        self.iteration_count_output.setText(_translate("MainWindow", "Итерация: 0"))
        self.next_iteration_btn.setText(_translate("MainWindow", ">>>"))
        self.menu.setTitle(_translate("MainWindow", "Фрактал"))
        self.save_image_action.setText(_translate("MainWindow", "Сохранить в файл"))
        self.configuration_action.setText(_translate("MainWindow", "Изменить конфигурацию"))
