# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/l_system_config_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.add_theorem_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_theorem_btn.setObjectName("add_theorem_btn")
        self.gridLayout.addWidget(self.add_theorem_btn, 2, 3, 1, 1)
        self.axiom_input = QtWidgets.QLineEdit(self.centralwidget)
        self.axiom_input.setObjectName("axiom_input")
        self.gridLayout.addWidget(self.axiom_input, 0, 3, 1, 1)
        self.theorems_sa = QtWidgets.QScrollArea(self.centralwidget)
        self.theorems_sa.setWidgetResizable(True)
        self.theorems_sa.setObjectName("theorems_sa")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 620, 303))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.theorems_sa.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.theorems_sa, 7, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.confirm_btn = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_btn.setObjectName("confirm_btn")
        self.gridLayout.addWidget(self.confirm_btn, 8, 0, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.rotate_angle_input = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rotate_angle_input.setEnabled(True)
        self.rotate_angle_input.setMinimum(1.0)
        self.rotate_angle_input.setMaximum(360.0)
        self.rotate_angle_input.setProperty("value", 90.0)
        self.rotate_angle_input.setObjectName("rotate_angle_input")
        self.gridLayout.addWidget(self.rotate_angle_input, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Изменение конфигурации"))
        self.add_theorem_btn.setText(_translate("MainWindow", "Добавить теорему"))
        self.label_2.setText(_translate("MainWindow", "Теоремы"))
        self.label.setText(_translate("MainWindow", "Аксиома"))
        self.confirm_btn.setText(_translate("MainWindow", "Подтвердить"))
        self.label_3.setText(_translate("MainWindow", "Угол поворота(градусы)"))
