# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/theorem_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.theorem_input = QtWidgets.QLineEdit(Form)
        self.theorem_input.setMinimumSize(QtCore.QSize(24, 24))
        self.theorem_input.setMaximumSize(QtCore.QSize(24, 24))
        self.theorem_input.setMaxLength(1)
        self.theorem_input.setObjectName("theorem_input")
        self.horizontalLayout.addWidget(self.theorem_input)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.theorem_output = QtWidgets.QLineEdit(Form)
        self.theorem_output.setMinimumSize(QtCore.QSize(0, 24))
        self.theorem_output.setMaximumSize(QtCore.QSize(16777215, 24))
        self.theorem_output.setObjectName("theorem_output")
        self.horizontalLayout.addWidget(self.theorem_output)
        self.delete_theorem_btn = QtWidgets.QPushButton(Form)
        self.delete_theorem_btn.setMinimumSize(QtCore.QSize(24, 24))
        self.delete_theorem_btn.setMaximumSize(QtCore.QSize(24, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_theorem_btn.setFont(font)
        self.delete_theorem_btn.setStyleSheet("background: red;")
        self.delete_theorem_btn.setObjectName("delete_theorem_btn")
        self.horizontalLayout.addWidget(self.delete_theorem_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "->"))
        self.delete_theorem_btn.setText(_translate("Form", "X"))
